table commodity_mapping
	excludeFromModelRefresh
	lineageTag: 8c257481-c80d-4117-9a0d-3ef73a71446a

	column Code
		dataType: string
		lineageTag: 267f8663-ca60-458a-9c42-d73553b8dae2
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 41571c76-16ec-49b6-b6d5-7371bc577def
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition commodity_mapping = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fVNNj5swEP0rVk6ttEirHKpeCXg3loC4fETNpntwidu1RAwFUzX/vrbBxqbZHhLA7828eZ6Z83kTbrfbzcP0eH04b6Jwl8AAhnm5x/Ic7kAAcI7SMD+t8cLgBYwOWewznstQwhH53lDw3BB+AepX0v7KOBEUhB735b/cF4eLqySxZDw2DeM/HbiERWnhkg7CwkmYKkNRQ67ddJIWyoF+qO8YpSgKUKYTxPIdID6IfrxSLohgLZ9YijRr5eHJUGfBntwWFkyg/PtSIWxYsKG16FlNGgB/jaxTqRf+/hiu+OrkHjOF0d5nprR+I/y9zBhhaJiYddRHPM8Kvmtcu5HGg93hK9Stt2YC6Z5xKgbwbXx83H4Cu/YPHZYoPS1+BCS9eDO98S7q3TvSLARjP5E6sCiWc+jDuGdX0t9A1EovjPvJigrjQ176osXYdW0vpvKnBsyV3emGbllcRaWB47G2I+f1c/r4NxhlQYIyaBiIAznR1MV92EdT7Auk0iPAcoXEvUIXv7rW2emEn+L8MC/P/nbpW+HsjpoPq7PMxsqOZi0SC88T8kZ3mdpVLs2ap9Yh2dnV+KLlTL+rlRVFAeYs07uJV1+2Cg35+hpXkWDeDRt+dzc0fSlHk91C9JYZOZlFXuzKsLuHzg1rxQ9x9tlsVkOH4aOOqLICwwg9TRtR8aGjNfvB6EWjxzA5KttH0vyWll//Ag==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Code = _t, Description = _t])
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

