table Dim_ROOM
	excludeFromModelRefresh
	lineageTag: 45aa3b42-ed87-4767-919a-ee4d98ef2d1a

	column ID
		dataType: string
		lineageTag: 88e3491a-ed45-46fb-8053-353c3ee06b46
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Final_Project_Name_Galleries
		dataType: string
		lineageTag: fd868fb7-877f-44fa-b93f-4a1d26217d94
		summarizeBy: none
		sourceColumn: Final_Project_Name_Galleries

		annotation SummarizationSetBy = Automatic

	column Final_Project_Name
		dataType: string
		lineageTag: 9dc45efd-073c-4b69-aa06-959a03e83ae7
		summarizeBy: none
		sourceColumn: Final_Project_Name

		annotation SummarizationSetBy = Automatic

	column 'Building Code'
		dataType: string
		lineageTag: a7bb9a0c-cbf3-4a4b-a04a-62c20daf8133
		summarizeBy: none
		sourceColumn: Building Code

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: f138545e-f0b4-4b79-ad34-374f8cab74c4
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column 'Building [2]'
		dataType: string
		lineageTag: 7a992f32-34a5-401b-b587-6127ed1530f0
		summarizeBy: none
		sourceColumn: Building [2]

		annotation SummarizationSetBy = Automatic

	column 'Building [3]'
		dataType: string
		lineageTag: 957b8d0d-a0c6-484a-bbcf-de7695f5c569
		summarizeBy: none
		sourceColumn: Building [3]

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 439bbbf0-7421-4ee1-8d83-1b0ba6c63b0f
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column 'Area Group'
		dataType: string
		lineageTag: 4ff51b9d-b3c3-44bb-b815-a0f74e61bfb1
		summarizeBy: none
		sourceColumn: Area Group

		annotation SummarizationSetBy = Automatic

	column Sub-Area
		dataType: string
		lineageTag: 6f207b82-1886-4169-816a-8cd6dadd7166
		summarizeBy: none
		sourceColumn: Sub-Area

		annotation SummarizationSetBy = Automatic

	column 'Item Name'
		dataType: string
		lineageTag: 8c17744c-225f-4b5a-847e-55d5f5fb9c50
		summarizeBy: none
		sourceColumn: Item Name

		annotation SummarizationSetBy = Automatic

	column 'Adjusted Room Name'
		dataType: string
		lineageTag: fcbda985-0d5c-4999-8868-277e974fea46
		summarizeBy: none
		sourceColumn: Adjusted Room Name

		annotation SummarizationSetBy = Automatic

	column 'Room Description'
		dataType: string
		lineageTag: 227dfb65-402b-4e4d-b8ba-ce402a166fe3
		summarizeBy: none
		sourceColumn: Room Description

		annotation SummarizationSetBy = Automatic

	column 'PDMS :3D-ErectionArea'
		dataType: string
		lineageTag: 7815553e-ffb0-48c1-9f2c-f876c537ec14
		summarizeBy: none
		sourceColumn: PDMS :3D-ErectionArea

		annotation SummarizationSetBy = Automatic

	column 'Space Type'
		dataType: string
		lineageTag: d485c06f-c05b-464f-bdef-751d600ed85e
		summarizeBy: none
		sourceColumn: Space Type

		annotation SummarizationSetBy = Automatic

	column 'Room Volume (m3)'
		dataType: string
		lineageTag: eabc12f5-913a-4319-9ad6-03a13d1e5390
		summarizeBy: none
		sourceColumn: Room Volume (m3)

		annotation SummarizationSetBy = Automatic

	column 'Room Floor Area (m2)'
		dataType: string
		lineageTag: 20752fe1-1ea3-44b9-9b34-297a04f1840c
		summarizeBy: none
		sourceColumn: Room Floor Area (m2)

		annotation SummarizationSetBy = Automatic

	column 'Room Wall Area (m2)'
		dataType: string
		lineageTag: 89622cdb-fa8d-4784-90e8-55d737e55290
		summarizeBy: none
		sourceColumn: Room Wall Area (m2)

		annotation SummarizationSetBy = Automatic

	column 'Room Zmin (m)'
		dataType: string
		lineageTag: 4b10ce6a-aa1a-4d98-a293-63a5d33cf889
		summarizeBy: none
		sourceColumn: Room Zmin (m)

		annotation SummarizationSetBy = Automatic

	column 'Room Zmax (m)'
		dataType: string
		lineageTag: 4f3c950f-bd52-48d3-a3f7-107f1302f870
		summarizeBy: none
		sourceColumn: Room Zmax (m)

		annotation SummarizationSetBy = Automatic

	column 'Erection Area'
		dataType: string
		lineageTag: ae82e07a-ef33-4baa-8409-784bcf988f7e
		summarizeBy: none
		sourceColumn: Erection Area

		annotation SummarizationSetBy = Automatic

	column 'Nominal Level (m)'
		dataType: string
		lineageTag: 51edea13-d19d-4b09-afe3-5dc58949c133
		summarizeBy: none
		sourceColumn: Nominal Level (m)

		annotation SummarizationSetBy = Automatic

	column 'zzz_HOC AC'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3060c216-3f11-417a-9c46-53ca635273d9
		summarizeBy: none
		sourceColumn: zzz_HOC AC

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'zzz_M3 Actual'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 90749f03-69d9-4e47-994c-cd8a03653944
		summarizeBy: none
		sourceColumn: zzz_M3 Actual

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'zzz_M3 Forecast'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ba91aaed-3011-4b5b-adc2-cf32b969cc8e
		summarizeBy: none
		sourceColumn: zzz_M3 Forecast

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'zzz_Room Status'
		dataType: string
		lineageTag: b9d491b5-ac10-4f72-b126-1c2374c99d29
		summarizeBy: none
		sourceColumn: zzz_Room Status

		annotation SummarizationSetBy = Automatic

	column 'zzz_M3 Requirement'
		dataType: string
		lineageTag: cabdfb17-9257-459f-a00d-ad1ea2939dca
		summarizeBy: none
		sourceColumn: zzz_M3 Requirement

		annotation SummarizationSetBy = Automatic

	column 'Final Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 799147ea-c1c6-4b26-acee-918ed7e6836d
		summarizeBy: none
		sourceColumn: Final Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Consolidated Handover milestone'
		dataType: string
		lineageTag: 730b6a87-fc46-4191-bf2d-76198be83a04
		summarizeBy: none
		sourceColumn: Consolidated Handover milestone

		annotation SummarizationSetBy = Automatic

	column 'TO3 Demand'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 49276eca-3b65-4c09-8783-de97c148aeda
		summarizeBy: none
		sourceColumn: TO3 Demand

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'TO4 Forecast'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 804c3fb5-dbe2-41c5-af7c-cdce859ca163
		summarizeBy: none
		sourceColumn: TO4 Forecast

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Published Room FC' =
			
			IF(
			    Dim_ROOM[zzz_HOC AC] <> BLANK(),
			    Dim_ROOM[zzz_HOC AC],
			    LOOKUPVALUE('Dim_Activity (LIVE_P6)'[Finish],'Dim_Activity (LIVE_P6)'[Activity ID], Dim_ROOM[Consolidated Handover milestone]
			))
		formatString: Short Date
		lineageTag: 77eff597-9763-4dc7-be4a-415ebe46bf07
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column MEH = IF(ISBLANK([budget_hours]), BLANK(), "MEH")
		lineageTag: eb5fb8ff-fe50-4958-a88b-04ab64186083
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Level
		dataType: string
		lineageTag: 1c697b1f-f05e-4b34-bc60-fe928d823e1c
		summarizeBy: none
		sourceColumn: Level

		annotation SummarizationSetBy = Automatic

	column Adj_Unit =
			
			IF(
			    Dim_ROOM[Unit] = "2",
			    "2","1/0/9"
			    )
		lineageTag: 76173ac1-a374-4323-9606-ca39d8fe8bdc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Dim_ROOM = m
		mode: import
		queryGroup: Dim_Room
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://edfenergynnb.sharepoint.com/sites/L4Analysts/Shared%20Documents/L4%20Analysts/00.%20Quantities/Room%20Tracker/ROOM%20TRACKER%20-%20LIVE.xlsx"), null, true),
				    ROOM_Sheet = Source{[Item="ROOM",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(ROOM_Sheet, [PromoteAllScalars=true]),
				    #"Removed Other Columns" = Table.SelectColumns(#"Promoted Headers",{"ID", "Final_Project_Name_Galleries", "Final_Project_Name", "Building Code", "Unit", "Building [2]", "Building [3]", "Area", "Area Group", "Sub-Area", "Item Name", "Adjusted Room Name", "Room Description", "PDMS :3D-ErectionArea", "Space Type", "Room Volume (m3)", "Room Floor Area (m2)", "Room Wall Area (m2)", "Room Zmin (m)", "Room Zmax (m)", "Erection Area", "Nominal Level (m)", "Level", "HOC AC", "M3 Requirement", "M3 Actual", "M3 Forecast", "Room Status", "Consolidated Handover milestone", "Final Date"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Final Date", type date}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type1",{{"M3 Forecast", type date}, {"M3 Actual", type date}, {"HOC AC", type date}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type", {{"Nominal Level (m)", null}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Errors",{{"HOC AC", "zzz_HOC AC"}, {"M3 Requirement", "zzz_M3 Requirement"}, {"M3 Actual", "zzz_M3 Actual"}, {"M3 Forecast", "zzz_M3 Forecast"}, {"Room Status", "zzz_Room Status"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Final_Project_Name_Galleries] <> null)),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"Adjusted Room Name"}, Dim_MCW, {"Adjusted Room Name"}, "Dim_MCW", JoinKind.LeftOuter),
				    #"Expanded Dim_MCW" = Table.ExpandTableColumn(#"Merged Queries", "Dim_MCW", {"TO3 Forecast", "TO4 Forecast"}, {"Dim_MCW.TO3 Forecast", "Dim_MCW.TO4 Forecast"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded Dim_MCW",{{"Dim_MCW.TO3 Forecast", "TO3 Demand"}, {"Dim_MCW.TO4 Forecast", "TO4 Forecast"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns1", {"Adjusted Room Name"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed Duplicates", each [Adjusted Room Name] <> null and [Adjusted Room Name] <> "")
				in
				    #"Filtered Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

