table Dim_Skill_Group
	excludeFromModelRefresh
	lineageTag: 43c1e7fd-68e3-4eb4-88f9-ab2bb0afa722

	column 'Skill Group'
		dataType: string
		lineageTag: 19ed5d17-2d84-4a95-89af-67484b91983d
		summarizeBy: none
		sourceColumn: Skill Group

		annotation SummarizationSetBy = Automatic

	column 'Trade Type'
		dataType: string
		lineageTag: 5471c134-d077-4a0d-87c3-2ff9befcc4c4
		summarizeBy: none
		sourceColumn: Trade Type

		annotation SummarizationSetBy = Automatic

	partition Dim_Skill_Group = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("bZFBTsNADEWvMsq6FWdAIdCgVkQE1EXUhZs4qVXXE00mcH2cigXEs7Pe9/yxv5smy+HM6HYgXbbJnihgG7PTpskK1ipQC/yfH7C9gFhe0YjumWLEsBIYDDsid2uWQxhRtNU9uFdPctdL2f5t8RBJhskKAfpoaLFU3tq8oJoDOyPs6jfDSpkiMCemUWXW3RIf7OHs55B4sqd+WcDwwxIRAU/b3PvQkaitmK7qo8gtBJKY+KrCcAPRQN1jZUUGsXkpndQqZcbz7Zzg7zQMCVyXVW1hC33vf+++kjREtFet51FT0e2kw8S4d/mLpsQBPuUq/tsmePThavI//QA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Skill Group" = _t, #"Trade Type" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Skill Group", type text}, {"Trade Type", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

