table 'Dynamic Dates'
	lineageTag: 8f5ec25a-0722-4bc9-9890-dcd7d1380b9a

	column PeriodKey
		dataType: int64
		formatString: 0
		lineageTag: 673ea73c-4f99-43d1-a8e9-4bceb5575bc2
		summarizeBy: count
		sourceColumn: PeriodKey

		annotation SummarizationSetBy = Automatic

	column PeriodLabel
		dataType: string
		lineageTag: e6e660ee-d26a-412d-afdc-eaed92256ace
		summarizeBy: none
		sourceColumn: PeriodLabel

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: ec477a9a-e7fe-407c-80ea-2ceb143dc790
		summarizeBy: none
		sourceColumn: StartDate

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: d4abefda-b7d2-4fc7-9655-348469249930
		summarizeBy: none
		sourceColumn: EndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Dynamic Dates' = m
		mode: import
		source =
				let
				    // --- Base dates ---
				    TodayDate = DateTime.Date(DateTime.LocalNow()),
				    CurrentYear = Date.Year(TodayDate),
				
				    // --- Last Sunday ---
				    LastSunday = Date.AddDays(
				        TodayDate,
				        -(Date.DayOfWeek(TodayDate, Day.Sunday))
				    ),
				
				    // --- Planned YTD ---
				    PlannedYTD =
				        #table(
				            {"PeriodKey", "PeriodLabel", "StartDate", "EndDate"},
				            {
				                {1, "Planned YTD", #date(CurrentYear, 1, 1), LastSunday}
				            }
				        ),
				
				    // --- Quarters ---
				    Quarters =
				        #table(
				            {"PeriodKey", "PeriodLabel", "StartDate", "EndDate"},
				            {
				                {2, "Q1", #date(CurrentYear, 1, 1),  #date(CurrentYear, 3, 31)},
				                {3, "Q2", #date(CurrentYear, 4, 1),  #date(CurrentYear, 6, 30)},
				                {4, "Q3", #date(CurrentYear, 7, 1),  #date(CurrentYear, 9, 30)},
				                {5, "Q4", #date(CurrentYear, 10, 1), #date(CurrentYear, 12, 31)}
				            }
				        ),
				
				    // --- Custom Planning Months ---
				    Months =
				        #table(
				            {"PeriodKey", "PeriodLabel", "StartDate", "EndDate"},
				            {
				                {6,  "Jul 26", #date(2026, 6, 29),  #date(2026, 7, 26)},
				                {7,  "Aug 26", #date(2026, 7, 27),  #date(2026, 8, 23)},
				                {8,  "Sep 26", #date(2026, 8, 24),  #date(2026, 10, 3)},
				                {9,  "Oct 26", #date(2026, 10, 4), #date(2026, 10, 25)},
				                {10, "Nov 26", #date(2026, 10, 26), #date(2026, 11, 23)},
				                {11, "Dec 26", #date(2026, 11, 24), #date(2026, 12, 27)}
				            }
				        ),
				
				    // --- Weekly Buckets ---
				    WeekStartDate = #date(2026, 6, 29),
				    WeekEndDate = #date(2026, 12, 27),
				
				    NumWeeks =
				        Number.RoundDown(
				            Duration.Days(WeekEndDate - WeekStartDate) / 7
				        ) + 1,
				
				    WeeksList =
				        List.Transform(
				            {0 .. NumWeeks - 1},
				            each
				                let
				                    StartDate = Date.AddDays(WeekStartDate, _ * 7),
				                    EndDate = Date.AddDays(StartDate, 6),
				                    WeekNo = _ + 1
				                in
				                    {
				                        11 + WeekNo,
				                        "W" & Text.PadStart(Text.From(WeekNo), 2, "0"),
				                        StartDate,
				                        EndDate
				                    }
				        ),
				
				    WeeksTable =
				        #table(
				            {"PeriodKey", "PeriodLabel", "StartDate", "EndDate"},
				            WeeksList
				        ),
				
				    // --- Combine all periods ---
				    Combined =
				        Table.Combine(
				            {
				                PlannedYTD,
				                Quarters,
				                Months,
				                WeeksTable
				            }
				        ),
				
				    // --- Set types ---
				    FinalTable =
				        Table.TransformColumnTypes(
				            Combined,
				            {
				                {"PeriodKey", Int64.Type},
				                {"PeriodLabel", type text},
				                {"StartDate", type date},
				                {"EndDate", type date}
				            }
				        )
				in
				    FinalTable

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

