table 'Equipment List (update 24/03)'
	isHidden
	excludeFromModelRefresh
	lineageTag: ab0e360d-3e53-41a3-a3af-9ccdfbcf7250

	column ECS
		dataType: string
		isHidden
		lineageTag: 10a9d573-f4f4-4764-8561-f49777ce6e21
		summarizeBy: none
		sourceColumn: ECS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Install Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: be083843-d9b5-4092-b136-476322ff72d1
		summarizeBy: none
		sourceColumn: Install Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Equipment List (update 24/03)' = m
		mode: import
		queryGroup: Actuals
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fdAxDoNADETRu2xNhD1rNlCCYiVdUBbSIO5/jSDSMq6fRt/ytiUd61OLYH7fUpMgreQWgpL25o+IMEdoFP27qmXh2CtHozgvH6hxNNo8MVh2yprVXwpRjoXgUCdHVpnGK1x8PYwsD7QQAXk4R0RoFDuTO2320UHD5Yf2Hw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ECS = _t, #"Install Date" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ECS", type text}, {"Install Date", type date}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

