table Fact_QF_Q
	excludeFromModelRefresh
	lineageTag: f8c5232c-08af-4587-a3fb-dece7be2dac1

	column 'Planning Commodity'
		dataType: string
		lineageTag: afa094d6-fe4e-4cc7-8cda-1f19b9a0eb5e
		summarizeBy: none
		sourceColumn: Planning Commodity

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: fe82fecf-bf3b-4ce5-82fa-3514aea322dc
		summarizeBy: none
		sourceColumn: Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Quantity
		dataType: double
		lineageTag: f4c88e8a-a7ae-4469-af20-b052dcadddc3
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_QF_Q = m
		mode: import
		queryGroup: Actuals
		source =
				let
				
				    // Get Excel file from SharePoint (replaces File.Contents)
				    Source =
				        Excel.Workbook(Web.Contents("https://edfenergynnb.sharepoint.com/sites/L4Analysts/Shared%20Documents/L4%20Analysts/01.%20L4SPE%20Dashboards/TO4/MEH-26%20FC.xlsx"), null, true),
				
				    // Select the worksheet
				    Sheet =
				        Source{[Item = "qQ target", Kind = "Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    #"Removed Other Columns" = Table.SelectColumns(#"Promoted Headers",{"Planning Commodity", "Date", "Quantity"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Quantity", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Planning Commodity] <> null))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

