table Fact_Booked_Hours
	lineageTag: d05b4e57-52fe-4eea-8481-7979dec901fa

	measure BookedHours_SumX =
			
			SUMX(
			    Fact_Booked_Hours,
			    Fact_Booked_Hours[Booked Hours]
			)
		formatString: 0
		lineageTag: 7a8ef800-8a83-4c19-a162-735b57b1b87a

	column Period
		dataType: dateTime
		formatString: Long Date
		lineageTag: bfb82c41-d973-4f5f-817b-c13ef255432f
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Booking Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b345b065-a80c-4217-8d81-b193bc70bec6
		summarizeBy: none
		sourceColumn: Booking Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Week Ending'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 732f04cc-c901-49f9-a782-6aed59d64e82
		summarizeBy: none
		sourceColumn: Week Ending

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Project
		dataType: string
		lineageTag: fd830027-9389-4572-9d93-57b90a9a23e6
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Job Code'
		dataType: string
		lineageTag: 47110ad2-90c5-467c-af39-8360c32dfa2b
		summarizeBy: none
		sourceColumn: Job Code

		annotation SummarizationSetBy = Automatic

	column Dir/Ind
		dataType: string
		lineageTag: fde241fb-d912-43ea-b233-33dfbb24696a
		summarizeBy: none
		sourceColumn: Dir/Ind

		annotation SummarizationSetBy = Automatic

	column Team
		dataType: string
		lineageTag: d5089539-e8bd-495b-954c-e40603313fd0
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

	column 'Skill Group'
		dataType: string
		lineageTag: 50dd92b0-1fbf-4313-be5a-3ceb3aa2d951
		summarizeBy: none
		sourceColumn: Skill Group

		annotation SummarizationSetBy = Automatic

	column 'Trade Type'
		dataType: string
		lineageTag: 49958f80-79fc-44d1-b8d3-aa04f6a34531
		summarizeBy: none
		sourceColumn: Trade Type

		annotation SummarizationSetBy = Automatic

	column 'Person Code'
		dataType: string
		lineageTag: b930cb66-3688-40ae-8f71-f6c814b131a5
		summarizeBy: none
		sourceColumn: Person Code

		annotation SummarizationSetBy = Automatic

	column 'MEH ID'
		dataType: string
		lineageTag: 9f760a69-ec8c-4c4b-8150-4fdd1e3a8e34
		summarizeBy: none
		sourceColumn: MEH ID

		annotation SummarizationSetBy = Automatic

	column 'Operative Name'
		dataType: string
		lineageTag: e880f2f8-4d80-497e-830b-bf08678b20c5
		summarizeBy: none
		sourceColumn: Operative Name

		annotation SummarizationSetBy = Automatic

	column 'Shift Code'
		dataType: string
		lineageTag: 2b3bccb1-b811-4341-9270-484a2de5b2ff
		summarizeBy: none
		sourceColumn: Shift Code

		annotation SummarizationSetBy = Automatic

	column 'Delay Code'
		dataType: string
		lineageTag: f4ced1d9-85ed-470a-8c7f-e2197396aac9
		summarizeBy: none
		sourceColumn: Delay Code

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Fact_Booked_Hours","TableItemName":"Delay Group","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Delay Description'
		dataType: string
		lineageTag: 86313637-833d-4a56-861d-83056d956071
		summarizeBy: none
		sourceColumn: Delay Description

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: bd6ed14b-f1bd-4169-9af0-37782c2b3827
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Booked Hours'
		dataType: double
		formatString: 0.00
		lineageTag: 67b637e1-cd8b-4209-b409-a6606a741d8d
		summarizeBy: sum
		sourceColumn: Booked Hours

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: string
		lineageTag: d99c8be5-0b16-4d0d-9704-369ea0e0301d
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	column 'Booking Group' =
			
			VAR DelayDesc = TRIM([Delay Description])
			VAR DashPos = FIND("-", DelayDesc, 1, 0)
			
			VAR Result =
			    IF(
			        DashPos = 0,
			        DelayDesc,
			        TRIM(MID(DelayDesc, DashPos + 1, LEN(DelayDesc)))
			    )
			
			RETURN
			    SUBSTITUTE(Result, "Resource Delay", "Resource Delays")
		lineageTag: 97f962c1-c24c-451f-99fe-e4fda5464c14
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Commodity =
			
			VAR JobCode = Fact_Booked_Hours[Job Code]
			VAR Project = Fact_Booked_Hours[Project Adjusted]
			
			VAR Area =
			    MAXX(
			        FILTER(
			            Dim_ROOM,
			            Dim_ROOM[Final_Project_Name] = Project
			        ),
			        Dim_ROOM[Area]
			    )
			
			VAR MatchedCode =
			    MAXX(
			        FILTER(
			            'Commodity Mapping Table',
			            CONTAINSSTRING(
			                JobCode,
			                'Commodity Mapping Table'[Code - Booked Hours ]
			            )
			        ),
			        'Commodity Mapping Table'[Code - Booked Hours ]
			    )
			
			RETURN
			IF(
			CONTAINSSTRING(JobCode, "CLAMP"),
			"CLAMPS",
			        IF(
			            CONTAINSSTRING(JobCode, "MECH-PIPE") &&
			            ISBLANK(MatchedCode),
			            IF(
			                CONTAINSSTRING(Area, "BOP"),
			                "MECH-PIPE-BOP",
			                IF(
			                    CONTAINSSTRING(Area, "NI"),
			                    "MECH-PIPE-NI",
			                    "MECH-PIPE"
			                )
			            ),
			            MatchedCode
			        )
			    )
		lineageTag: 5a8bc29c-4c91-4e00-9d2f-00b76e1313f5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column area =
			CALCULATE(
			        MAX(Dim_ROOM[Area]),
			        FILTER(
			            Dim_ROOM,
			            Dim_ROOM[Final_Project_Name] = Fact_Booked_Hours[Project Adjusted]))
		lineageTag: b164ab8c-b7f2-4b41-988c-1eea5d72c811
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Is_Latest_Date =
			var maxdate = CALCULATE(MAX(Fact_Booked_Hours[Booking Date]),all(Fact_Booked_Hours)) RETURN
			Fact_Booked_Hours[Booking Date]=maxdate
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 539f8633-1849-45d6-894a-1f9f00ff0903
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Room =
			
			VAR DotPos = SEARCH(".", 'Fact_Booked_Hours'[Job Code], 1, 0)
			RETURN
			IF(
			    DotPos > 0,
			    LEFT('Fact_Booked_Hours'[Job Code], DotPos - 1),
			    'Fact_Booked_Hours'[Job Code]
			)
		lineageTag: 927b5701-c70e-4a91-8528-8b7524a2a39a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Welder_Code = related(Welders[Code])
		lineageTag: 945a8b4f-9dde-4960-9b77-c8493128889c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Project Adjusted'
		dataType: string
		lineageTag: bf912af4-0c29-4745-8f36-13dfb8956cd8
		summarizeBy: none
		sourceColumn: Project Adjusted

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: aeff3127-4f04-49c8-9645-def1591bfe67
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column CategoryGroup
		dataType: string
		lineageTag: 7573574f-6b77-405f-bb2c-0e1597a1832d
		summarizeBy: none
		sourceColumn: CategoryGroup

		annotation SummarizationSetBy = Automatic

	column RollupGroup
		dataType: string
		lineageTag: f47b4e13-8ab6-410f-8048-36675d6b7942
		summarizeBy: none
		sourceColumn: RollupGroup

		annotation SummarizationSetBy = Automatic

	column 'Delay Group' =
			SWITCH(
				TRUE,
				ISBLANK('Fact_Booked_Hours'[Delay Code]),
				"(Blank)",
				'Fact_Booked_Hours'[Delay Code] IN {"I010",
					"I011",
					"I012",
					"I013",
					"I020",
					"I021",
					"I022",
					"I030",
					"I040",
					"I041",
					"I042",
					"I043",
					"I050",
					"I051",
					"I060",
					"I061",
					"I062",
					"I063",
					"I064",
					"I065",
					"I070",
					"I071",
					"I072",
					"I073",
					"I074",
					"I075",
					"I076",
					"I077",
					"I078",
					"I080",
					"I081",
					"I090",
					"I091",
					"I092",
					"I100",
					"I110",
					"I111",
					"I112",
					"I120",
					"I121",
					"I130",
					"I131",
					"I132",
					"I133",
					"I134",
					"I135",
					"I136",
					"I140",
					"I141",
					"I142",
					"I150",
					"I151",
					"I152",
					"I160",
					"I161",
					"I162",
					"I163",
					"I200"},
				"Delay",
				'Fact_Booked_Hours'[Delay Code] IN {"D01"},
				"Direct",
				'Fact_Booked_Hours'[Delay Code]
			)
		lineageTag: 3152896a-9feb-4b9b-9ad3-940a0e1c7b45
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Fact_Booked_Hours"
				          }
				        },
				        "Property": "Delay Code"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"f","Entity":"Fact_Booked_Hours"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Delay Code"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"Delay","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Delay Code"}}],"Values":[[{"Literal":{"Value":"'I010'"}}],[{"Literal":{"Value":"'I011'"}}],[{"Literal":{"Value":"'I012'"}}],[{"Literal":{"Value":"'I013'"}}],[{"Literal":{"Value":"'I020'"}}],[{"Literal":{"Value":"'I021'"}}],[{"Literal":{"Value":"'I022'"}}],[{"Literal":{"Value":"'I030'"}}],[{"Literal":{"Value":"'I040'"}}],[{"Literal":{"Value":"'I041'"}}],[{"Literal":{"Value":"'I042'"}}],[{"Literal":{"Value":"'I043'"}}],[{"Literal":{"Value":"'I050'"}}],[{"Literal":{"Value":"'I051'"}}],[{"Literal":{"Value":"'I060'"}}],[{"Literal":{"Value":"'I061'"}}],[{"Literal":{"Value":"'I062'"}}],[{"Literal":{"Value":"'I063'"}}],[{"Literal":{"Value":"'I064'"}}],[{"Literal":{"Value":"'I065'"}}],[{"Literal":{"Value":"'I070'"}}],[{"Literal":{"Value":"'I071'"}}],[{"Literal":{"Value":"'I072'"}}],[{"Literal":{"Value":"'I073'"}}],[{"Literal":{"Value":"'I074'"}}],[{"Literal":{"Value":"'I075'"}}],[{"Literal":{"Value":"'I076'"}}],[{"Literal":{"Value":"'I077'"}}],[{"Literal":{"Value":"'I078'"}}],[{"Literal":{"Value":"'I080'"}}],[{"Literal":{"Value":"'I081'"}}],[{"Literal":{"Value":"'I090'"}}],[{"Literal":{"Value":"'I091'"}}],[{"Literal":{"Value":"'I092'"}}],[{"Literal":{"Value":"'I100'"}}],[{"Literal":{"Value":"'I110'"}}],[{"Literal":{"Value":"'I111'"}}],[{"Literal":{"Value":"'I112'"}}],[{"Literal":{"Value":"'I120'"}}],[{"Literal":{"Value":"'I121'"}}],[{"Literal":{"Value":"'I130'"}}],[{"Literal":{"Value":"'I131'"}}],[{"Literal":{"Value":"'I132'"}}],[{"Literal":{"Value":"'I133'"}}],[{"Literal":{"Value":"'I134'"}}],[{"Literal":{"Value":"'I135'"}}],[{"Literal":{"Value":"'I136'"}}],[{"Literal":{"Value":"'I140'"}}],[{"Literal":{"Value":"'I141'"}}],[{"Literal":{"Value":"'I142'"}}],[{"Literal":{"Value":"'I150'"}}],[{"Literal":{"Value":"'I151'"}}],[{"Literal":{"Value":"'I152'"}}],[{"Literal":{"Value":"'I160'"}}],[{"Literal":{"Value":"'I161'"}}],[{"Literal":{"Value":"'I162'"}}],[{"Literal":{"Value":"'I163'"}}],[{"Literal":{"Value":"'I200'"}}]]}}},{"DisplayName":"Direct","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Delay Code"}}],"Values":[[{"Literal":{"Value":"'D01'"}}]]}}}]}

		annotation SummarizationSetBy = Automatic

	partition Fact_Booked_Hours = m
		mode: import
		queryGroup: Actuals
		source = ```
				let
				    Source = PowerPlatform.Dataflows([]),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"08b2498c-771b-444f-8d6c-866ef825ad96" = Workspaces{[workspaceId="08b2498c-771b-444f-8d6c-866ef825ad96"]}[Data],
				    #"e127115e-fce7-46b8-9d0d-1ed78fd62665" = #"08b2498c-771b-444f-8d6c-866ef825ad96"{[dataflowId="e127115e-fce7-46b8-9d0d-1ed78fd62665"]}[Data],
				    Fact_Booked_Hours_ = #"e127115e-fce7-46b8-9d0d-1ed78fd62665"{[entity="Fact_Booked_Hours",version=""]}[Data],
				
				    // Load the mapping table into a buffered list once, for performance
				    MappingTable = Table.Buffer(Dim_Job_Code_Category),
				
				    // Function: given a Job Code, find its matching row in the mapping table
				    MatchJobCode = (code as nullable text) as record =>
				        let
				            code_ = if code = null then "" else Text.Upper(Text.Trim(code)),
				            // 1. Try Exact match first
				            ExactMatch = Table.SelectRows(MappingTable, each 
				                [Match Type] = "Exact" and Text.Upper(Text.Trim([Job Code])) = code_
				            ),
				            // 2. Try Starts With (strip trailing * from pattern)
				            StartsWithMatch = Table.SelectRows(MappingTable, each
				                [Match Type] = "Starts With" and
				                Text.StartsWith(code_, Text.Upper(Text.Trim(Text.Replace([Job Code], "*", ""))))
				            ),
				            // 3. Try Contains (strip leading/trailing * from pattern)
				            ContainsMatch = Table.SelectRows(MappingTable, each
				                [Match Type] = "Contains" and
				                Text.Contains(code_, Text.Upper(Text.Trim(Text.Replace([Job Code], "*", ""))))
				            ),
				            Result =
				                if Table.RowCount(ExactMatch) > 0 then ExactMatch{0}
				                else if Table.RowCount(StartsWithMatch) > 0 then StartsWithMatch{0}
				                else if Table.RowCount(ContainsMatch) > 0 then ContainsMatch{0}
				                else [Category = "Uncategorised - " & code, CategoryGroup = "Uncategorised", RollupGroup = "Uncategorised"]
				        in
				            Result,
				
				    // Apply the match function to every row, returning a record column
				    #"Added Match Record" = Table.AddColumn(Fact_Booked_Hours_, "MatchResult", each MatchJobCode([Job Code])),
				
				    // Expand the record into three separate columns
				    #"Expanded Match" = Table.ExpandRecordColumn(#"Added Match Record", "MatchResult", 
				        {"Category", "CategoryGroup", "RollupGroup"}, 
				        {"Category", "CategoryGroup", "RollupGroup"}
				    )
				in
				    #"Expanded Match"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

