table Bridge_commodity_map
	excludeFromModelRefresh
	lineageTag: f0556219-4623-4fbf-843f-74e43fb8d0d1

	column Fact_TO4_Q
		dataType: string
		lineageTag: e6ac8e51-ef45-4a3c-8ad7-c62168509c23
		summarizeBy: none
		sourceColumn: Fact_TO4_Q

		annotation SummarizationSetBy = Automatic

	column 'Planning Commodity'
		dataType: string
		lineageTag: 90ad41a6-7923-4bdf-82f5-4a1ccedf8db6
		summarizeBy: none
		sourceColumn: Planning Commodity

		annotation SummarizationSetBy = Automatic

	partition Bridge_commodity_map = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://edfenergynnb.sharepoint.com/sites/L4Analysts/Shared%20Documents/L4%20Analysts/00.%20Quantities/Bridge_Commotidy_map.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Trimmed Text" = Table.TransformColumns(#"Promoted Headers",{{"Fact_TO4_Q", Text.Trim, type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Trimmed Text",{{"dim_ecs", "Planning Commodity"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

