table 'Commodity Mapping Table'
	excludeFromModelRefresh
	lineageTag: cfdf3fd9-6b97-4fa2-9134-5665c59adfbd

	column 'Fact - Commodity'
		dataType: string
		lineageTag: 015e764f-eb61-4fcb-80d4-b99594e8ff9f
		summarizeBy: none
		sourceColumn: Fact - Commodity

		annotation SummarizationSetBy = Automatic

	column 'Code - Booked Hours '
		dataType: string
		lineageTag: 8d82c79c-a9b4-4c4e-94fc-206a2a5abba8
		summarizeBy: none
		sourceColumn: "Code - Booked Hours "

		annotation SummarizationSetBy = Automatic

	column Commodity = ```
			
			VAR Lookup = 
			    LOOKUPVALUE(
			        commodity_mapping[Description],
			        commodity_mapping[Code],
			        'Commodity Mapping Table'[Code - Booked Hours ]
			    )
			
			RETURN
			    IF(
			        ISBLANK(Lookup),
			        'Commodity Mapping Table'[Fact - Commodity],
			        Lookup
			    )
			```
		lineageTag: f7eaf6bc-4ead-40a6-a484-2c7b64faa1f7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Commodity Mapping Table' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://edfenergynnb.sharepoint.com/sites/L4Analysts/Shared%20Documents/L4%20Analysts/00.%20Quantities/Commodity%20Mapping%20Booked%20Hours.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Filtered Rows" = Table.SelectRows(#"Promoted Headers", each [#"Fact - Commodity"] <> null and [#"Fact - Commodity"] <> "")
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

