table Dim_WeldEye
	excludeFromModelRefresh
	lineageTag: e08d3169-0de0-4ea1-b5b3-078276f2b631

	column 'ECS Code'
		dataType: string
		lineageTag: 530f8dec-8adb-4c6b-b166-360c229b5a6d
		summarizeBy: none
		sourceColumn: ECS Code

		annotation SummarizationSetBy = Automatic

	column 'Actual Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3f773a1f-b4e6-4639-991c-1f06013f0511
		summarizeBy: none
		sourceColumn: Actual Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Dim_WeldEye = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://edfenergynnb.sharepoint.com/sites/L4Analysts/Shared%20Documents/L4%20Analysts/43.%20Weldeye/WeldEyeDataDump%20-%20Unit%201%20Piping.xlsx"), null, true),
				    WeldEye_Sheet = Source{[Item="WeldEye",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(WeldEye_Sheet, [PromoteAllScalars=true]),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Promoted Headers", [PromoteAllScalars=true]),
				    #"Removed Other Columns" = Table.SelectColumns(#"Promoted Headers1",{"Drawing", "Weld no.", "Prod. time"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each [Prod. time] <> null and [Prod. time] <> ""),
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "Custom", each Text.Select([#"Weld no."], {"0".."9"})),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"Weld no."}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Custom", "Weld no."}, {"Prod. time", "Actual Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Actual Date", type datetime}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Actual Date", type date}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "ECS Code", each [Drawing]&"-"&[#"Weld no."]),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Added Custom1",{"ECS Code", "Actual Date"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns1", {"ECS Code"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

