table Dim_IWS12_QM
	excludeFromModelRefresh
	lineageTag: 0b578886-3e2c-450a-9ac7-261c42d04e55

	column 'ECS Code'
		dataType: string
		lineageTag: 71ff4ac2-2191-4896-88d6-eb35cac0ee41
		summarizeBy: none
		sourceColumn: ECS Code

		annotation SummarizationSetBy = Automatic

	column 'IWS_11.1 - Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5c9a0487-71d1-44a7-be7d-7d33b271c0de
		summarizeBy: none
		sourceColumn: IWS_11.1 - Start Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'IWS_11.1 - Finish Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6b4e4123-c5ca-452d-8557-79ed44b6b8a6
		summarizeBy: none
		sourceColumn: IWS_11.1 - Finish Date

		annotation SummarizationSetBy = Automatic

	column 'IWS_12 -  Start Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 687095fa-4b77-4714-8919-68bebd6c36ab
		summarizeBy: none
		sourceColumn: IWS_12 -  Start Date

		annotation SummarizationSetBy = Automatic

	column 'IWS_12 -  Finish Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: f430be69-65e0-4c9c-a2b1-88b2b8a69677
		summarizeBy: none
		sourceColumn: IWS_12 -  Finish Date

		annotation SummarizationSetBy = Automatic

	column 'IWS_12 - SND'
		dataType: dateTime
		formatString: General Date
		lineageTag: 3607b71f-545b-4da5-b9b1-916fae3eb266
		summarizeBy: none
		sourceColumn: IWS_12 - SND

		annotation SummarizationSetBy = Automatic

	column 'Activity ID'
		dataType: string
		lineageTag: 2e8b6108-0d45-4e2d-873d-159c5ef9468d
		summarizeBy: none
		sourceColumn: Activity ID

		annotation SummarizationSetBy = Automatic

	partition Dim_IWS12_QM = m
		mode: import
		queryGroup: Actuals
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"08b2498c-771b-444f-8d6c-866ef825ad96" = Workspaces{[workspaceId="08b2498c-771b-444f-8d6c-866ef825ad96"]}[Data],
				    #"1fc0d6bc-e6df-4a6d-bf52-3a085f97e215" = #"08b2498c-771b-444f-8d6c-866ef825ad96"{[dataflowId="1fc0d6bc-e6df-4a6d-bf52-3a085f97e215"]}[Data],
				    IWS12_QM_ = #"1fc0d6bc-e6df-4a6d-bf52-3a085f97e215"{[entity="IWS12_QM",version=""]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(IWS12_QM_,{"ECS Code", "Activity ID", "IWS_11.1 - Start Date", "IWS_11.1 - Finish Date", "IWS_12 -  Start Date", "IWS_12 -  Finish Date", "IWS_12 - SND"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

