table Dim_MEH_ENG
	lineageTag: 133f4b54-de7c-47ed-9502-d6c955e9acb3

	column Scope
		dataType: string
		lineageTag: 69ef6bbb-f7d6-4a3a-a5cb-edf6d5aad332
		summarizeBy: none
		sourceColumn: Scope

		annotation SummarizationSetBy = Automatic

	column 'Forecast Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0441c105-9d26-45e0-bf76-b79eaa55863a
		summarizeBy: none
		sourceColumn: Forecast Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Length (m)'
		dataType: double
		lineageTag: f9431524-732a-4328-a243-00c933edcbb3
		summarizeBy: none
		sourceColumn: Length (m)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DTS
		dataType: string
		lineageTag: cb3e9217-4809-4391-a3da-7e2fa3989f60
		summarizeBy: none
		sourceColumn: DTS

		annotation SummarizationSetBy = Automatic

	column 'Manufacturing Status'
		dataType: string
		lineageTag: c27f0abf-e583-4cd5-8bf9-493b9c4962b2
		summarizeBy: none
		sourceColumn: Manufacturing Status

		annotation SummarizationSetBy = Automatic

	column RfC
		dataType: string
		lineageTag: 44680894-8ece-4246-ab5d-a93abdd66d9b
		summarizeBy: none
		sourceColumn: RfC

		annotation SummarizationSetBy = Automatic

	column RfM
		dataType: string
		lineageTag: a28ef161-ef33-48b2-8214-644fc3770d1c
		summarizeBy: none
		sourceColumn: RfM

		annotation SummarizationSetBy = Automatic

	column HO3
		dataType: string
		lineageTag: f299540f-6932-44ba-bcef-d0065dfec57b
		summarizeBy: none
		sourceColumn: HO3

		annotation SummarizationSetBy = Automatic

	column EMC
		dataType: string
		lineageTag: 4e804658-5a99-4f50-b0e1-6aa3e08b1d28
		summarizeBy: none
		sourceColumn: EMC

		annotation SummarizationSetBy = Automatic

	column FCR
		dataType: string
		lineageTag: 5b582005-535c-4aa4-9558-db9e0a2ae61e
		summarizeBy: none
		sourceColumn: FCR

		annotation SummarizationSetBy = Automatic

	column Sub-Scope
		dataType: string
		lineageTag: e1c47a16-92e4-44ba-b933-362f60a2eda7
		summarizeBy: none
		sourceColumn: Sub-Scope

		annotation SummarizationSetBy = Automatic

	column Dummy
		dataType: string
		lineageTag: d3c86a0f-2fb0-4f93-9e66-50a751d8b7fe
		summarizeBy: none
		sourceColumn: Dummy

		annotation SummarizationSetBy = Automatic

	column 'RfM TF'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e987d07d-6722-42e7-a393-9864ad3916fd
		summarizeBy: none
		sourceColumn: RfM TF

		annotation SummarizationSetBy = Automatic

	column 'HO3 TF'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8520096f-d08d-4296-8e8a-d93497a1de68
		summarizeBy: none
		sourceColumn: HO3 TF

		annotation SummarizationSetBy = Automatic

	column 'DTS TF'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4a17d46e-94f8-4a76-8d28-0ac68b68774b
		summarizeBy: none
		sourceColumn: DTS TF

		annotation SummarizationSetBy = Automatic

	column 'RfC TF'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d60829b0-b776-43f9-a07c-d45dca87f7c6
		summarizeBy: none
		sourceColumn: RfC TF

		annotation SummarizationSetBy = Automatic

	column 'EMC TF'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0b1222a6-e902-40bb-85af-f80463d5d24b
		summarizeBy: none
		sourceColumn: EMC TF

		annotation SummarizationSetBy = Automatic

	column System
		dataType: string
		lineageTag: 4b16a836-8358-4c11-8453-cef46cabedb8
		summarizeBy: none
		sourceColumn: System

		annotation SummarizationSetBy = Automatic

	column 'Scope Asset Type'
		dataType: string
		lineageTag: 0ee66b4b-499e-41b0-a90a-d1a8ec828afe
		summarizeBy: none
		sourceColumn: Scope Asset Type

		annotation SummarizationSetBy = Automatic

	column 'Sub-Scope Asset Type'
		dataType: string
		lineageTag: 5f0d8e08-abb3-4305-b941-a06f7953c6c9
		summarizeBy: none
		sourceColumn: Sub-Scope Asset Type

		annotation SummarizationSetBy = Automatic

	column 'HO1 Count'
		dataType: int64
		formatString: 0
		lineageTag: f0bfbc86-0746-46dd-acf1-7b5758341510
		summarizeBy: none
		sourceColumn: HO1 Count

		annotation SummarizationSetBy = Automatic

	column 'ECS Code'
		dataType: string
		lineageTag: c56a4298-1322-4356-be4a-86f0fd926b82
		summarizeBy: none
		sourceColumn: ECS Code

		annotation SummarizationSetBy = Automatic

	partition Dim_MEH_ENG = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"49a4e3ac-8c02-40ad-8497-ef822a42e646" = Workspaces{[workspaceId="49a4e3ac-8c02-40ad-8497-ef822a42e646"]}[Data],
				    #"21fa62c6-f873-400c-b48a-4f96fc1fb9d3" = #"49a4e3ac-8c02-40ad-8497-ef822a42e646"{[dataflowId="21fa62c6-f873-400c-b48a-4f96fc1fb9d3"]}[Data],
				    #"EPM High Level_" = #"21fa62c6-f873-400c-b48a-4f96fc1fb9d3"{[entity="EPM High Level",version=""]}[Data],
				
				    #"Renamed Columns" = Table.RenameColumns(
				        #"EPM High Level_",
				        {
				            {"FC/ACTUAL", "Forecast Date"},
				            {"Manu Status", "Manufacturing Status"},
				            {"Asset ECS", "ECS Code"}
				        }
				    ),
				
				    #"Reordered Columns" = Table.ReorderColumns(
				        #"Renamed Columns",
				        {
				            "Scope", "ECS Code", "Forecast Date", "DTS",
				            "Manufacturing Status", "RfC", "RfM", "HO3",
				            "EMC", "FCR", "ECS Branch", "Room ECS", "Asset Type"
				        }
				    ),
				
				    #"Removed Columns" = Table.RemoveColumns(
				        #"Reordered Columns",
				        {"ECS Branch", "Room ECS", "Asset Type"}
				    ),
				
				    #"Added Custom" = Table.AddColumn(
				        #"Removed Columns",
				        "ECS Code a",
				        each
				            let
				                Code = [ECS Code],
				
				                FixedSPL =
				                    if Text.EndsWith(Code, "SPL0") then Text.Replace(Code, "SPL0", "SPL00") else
				                    if Text.EndsWith(Code, "SPL1") then Text.Replace(Code, "SPL1", "SPL01") else
				                    if Text.EndsWith(Code, "SPL2") then Text.Replace(Code, "SPL2", "SPL02") else
				                    if Text.EndsWith(Code, "SPL3") then Text.Replace(Code, "SPL3", "SPL03") else
				                    if Text.EndsWith(Code, "SPL4") then Text.Replace(Code, "SPL4", "SPL04") else
				                    if Text.EndsWith(Code, "SPL5") then Text.Replace(Code, "SPL5", "SPL05") else
				                    if Text.EndsWith(Code, "SPL6") then Text.Replace(Code, "SPL6", "SPL06") else
				                    if Text.EndsWith(Code, "SPL7") then Text.Replace(Code, "SPL7", "SPL07") else
				                    if Text.EndsWith(Code, "SPL8") then Text.Replace(Code, "SPL8", "SPL08") else
				                    if Text.EndsWith(Code, "SPL9") then Text.Replace(Code, "SPL9", "SPL09") else
				                    Code,
				
				                FinalCode =
				                    if Text.Contains(FixedSPL, "-SPL")
				                    then Text.Replace(FixedSPL, "-SPL", "SPL")
				                    else FixedSPL
				            in
				                FinalCode
				    ),
				
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom", {"ECS Code"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1", {{"ECS Code a", "ECS Code"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns1", {{"Forecast Date", type date}}),
				
				    // Create duplicate records with "-" appended to ECS Code
				    #"Duplicated Rows" = Table.TransformColumns(
				        #"Changed Type",
				        {{"ECS Code", each _ & "-", type text}}
				    ),
				
				    // Combine original and duplicated records
				    #"Combined Tables" = Table.Combine(
				        {
				            #"Changed Type",
				            #"Duplicated Rows"
				        }
				    ),
				    #"Removed Duplicates" = Table.Distinct(#"Combined Tables", {"ECS Code"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

