table Dim_Activities
	excludeFromModelRefresh
	lineageTag: 33f09dc8-7098-4872-b96c-2e72225a6ffb

	column 'Project ID'
		dataType: string
		lineageTag: 61f5181e-bcd0-4a0c-80f8-1d2692154442
		summarizeBy: none
		sourceColumn: Project ID

		annotation SummarizationSetBy = Automatic

	column 'Activity ID'
		dataType: string
		lineageTag: 224e76fd-3818-44de-817d-cd9b3c404f1f
		summarizeBy: none
		sourceColumn: Activity ID

		annotation SummarizationSetBy = Automatic

	column Room
		dataType: string
		lineageTag: b510df21-3907-4270-b2c5-0a64014b69f1
		summarizeBy: none
		sourceColumn: Room

		annotation SummarizationSetBy = Automatic

	column Key_Left
		dataType: string
		lineageTag: 5080bede-725a-416b-b643-e8d0cccb0ff7
		summarizeBy: none
		sourceColumn: Key_Left

		annotation SummarizationSetBy = Automatic

	column Key_Right
		dataType: string
		lineageTag: eafca115-4898-40fd-89cf-c69155d876fb
		summarizeBy: none
		sourceColumn: Key_Right

		annotation SummarizationSetBy = Automatic

	column OBJECT_KEY
		dataType: string
		lineageTag: 79dc4a11-58d4-4c6c-93c7-9ad54b41bd71
		summarizeBy: none
		sourceColumn: OBJECT_KEY

		annotation SummarizationSetBy = Automatic

	partition Dim_Activities = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://edfenergynnb.sharepoint.com/sites/L4Analysts/Shared%20Documents/L4%20Analysts/01.%20L4SPE%20Dashboards/TO4/TO4%202ND%20PASS/Archive/PBI%20QTY%20-%20TO4%20Data%20Extract.xlsx"), null, true),
				
				    Activities_Sheet = Source{[Item="Activities",Kind="Sheet"]}[Data],
				
				    #"Removed Top Rows" =
				        Table.Skip(Activities_Sheet, 1),
				
				    #"Trimmed Text" =
				        Table.TransformColumns(#"Removed Top Rows",
				            {{"Column1", each if _ = null then null else Text.Trim(_), type text}}
				        ),
				
				    #"Promoted Headers" =
				        Table.PromoteHeaders(#"Trimmed Text", [PromoteAllScalars = true]),
				
				
				    // Keep required columns early (performance critical)
				    ColumnsKept =
				        Table.SelectColumns(
				            #"Promoted Headers",
				            {"Project ID","Activity ID","Activity Name","Finish","Budgeted Labor Units"}
				        ),
				
				    // One single type conversion pass
				    Typed =
				        Table.TransformColumnTypes(
				            ColumnsKept,
				            {
				                {"Project ID", type text},
				                {"Activity ID", type text},
				                {"Activity Name", type text},
				                {"Finish", type text}
				            }
				        ),
				
				    // Filter early (huge speed boost)
				    FilteredProject =
				        Table.SelectRows(
				            Typed,
				            each Text.StartsWith([Project ID], "MEHA_U")
				        ),
				
				
				    // ----------- FINISH COLUMN PROCESSING -----------------
				
				    FinishSplit =
				        Table.SplitColumn(
				            FilteredProject,
				            "Finish",
				            Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, true),
				            {"Finish_Date", "Finish_Text"}
				        ),
				
				    FilteredFinish =
				        Table.SelectRows(
				            FinishSplit,
				            each [Finish_Text] = null
				        ),
				
				    FinishClean =
				        Table.RemoveColumns(
				            FilteredFinish,
				            {"Finish_Date","Finish_Text","Budgeted Labor Units"}
				        ),
				
				
				    #"Split Column by Delimiter" =
				        Table.SplitColumn(
				            FinishClean,
				            "Activity Name",
				            Splitter.SplitTextByEachDelimiter({"-"}, QuoteStyle.Csv, false),
				            {"Activity Name.1", "Activity Name.2"}
				        ),
				
				    #"Renamed Columns" =
				        Table.RenameColumns(
				            #"Split Column by Delimiter",
				            {
				                {"Activity Name.1", "Room"},
				                {"Activity Name.2", "Activity_Right"}
				            }
				        ),
				
				
				    // Faster ZL prefix logic (no double scan)
				    RoomFixed =
				        Table.TransformColumns(
				            #"Renamed Columns",
				            {
				                {"Room",
				                    each if _ <> null and Text.StartsWith(_, "ZL") and not Text.StartsWith(_, "ZL-")
				                         then "ZL-" & Text.AfterDelimiter(_, "ZL")
				                         else _,
				                    type text
				                }
				            }
				        ),
				
				
				    // Split Activity_Right into two parts
				    ActivityNameCopySplit =
				        Table.SplitColumn(
				            RoomFixed,
				            "Activity_Right",
				            Splitter.SplitTextByDelimiter(".", QuoteStyle.Csv),
				            {"Key_Left","Key_Right"}
				        ),
				
				    FilteredKey =
				        Table.SelectRows(
				            ActivityNameCopySplit,
				            each [Key_Right] <> null and [Key_Right] <> ""
				        ),
				
				
				    // ----------- FINAL OBJECT KEY -----------------
				
				    // Buffer is used at the correct point
				    Buffered =
				        Table.Buffer(FilteredKey),
				
				    // Avoid double prefix fix; this replaces only incorrect cases
				    #"Replaced Value" =
				        Table.ReplaceValue(
				            Buffered,
				            "ZL",
				            "ZL-",
				            Replacer.ReplaceText,
				            {"Room"}
				        ),
				
				    AddedObjectKey =
				        Table.AddColumn(
				            #"Replaced Value",
				            "OBJECT_KEY",
				            each [Room] & "." & [Key_Right],
				            type text
				        ),
				
				    Final =
				        Table.ReorderColumns(
				            AddedObjectKey,
				            {"Project ID","Activity ID","Room","Key_Left","Key_Right","OBJECT_KEY"}
				        )
				in
				    Final

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

