table Dim_Contract
	lineageTag: 0b1044b0-41e8-41ad-ae09-6f7b244440a8

	column ECS
		dataType: string
		lineageTag: 0477c578-b032-4858-8610-508dd84dfb9c
		summarizeBy: none
		sourceColumn: ECS

		annotation SummarizationSetBy = Automatic

	column 'Installation Contract'
		dataType: string
		lineageTag: 6316c222-5d93-40f6-8b14-746c7eb866e7
		summarizeBy: none
		sourceColumn: Installation Contract

		annotation SummarizationSetBy = Automatic

	column 'Supplier Contract'
		dataType: string
		lineageTag: 260d0aeb-e76e-4734-bbc5-ea2e634739ba
		summarizeBy: none
		sourceColumn: Supplier Contract

		annotation SummarizationSetBy = Automatic

	column 'Contract Source'
		dataType: string
		lineageTag: 9947d23a-5cbc-40d5-9276-a677644ecaff
		summarizeBy: none
		sourceColumn: Contract Source

		annotation SummarizationSetBy = Automatic

	column PCR
		dataType: string
		lineageTag: 3c5edb91-b5d1-4193-a365-087fe4e4ff2c
		summarizeBy: none
		sourceColumn: PCR

		annotation SummarizationSetBy = Automatic

	column AMI
		dataType: string
		lineageTag: ed702ae3-f85d-4025-9bfc-ab374f55eb81
		summarizeBy: none
		sourceColumn: AMI

		annotation SummarizationSetBy = Automatic

	column 'Modified by'
		dataType: string
		lineageTag: 829215e0-b984-4c2f-b52b-de8ed943e0b8
		summarizeBy: none
		sourceColumn: Modified by

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: string
		lineageTag: 04f5fa8d-e195-4143-8259-b86b8b776687
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column Notes
		dataType: string
		lineageTag: 0c454919-da34-45ea-9357-a9ae5608fb80
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: 233c67f8-f65e-460a-9097-4923c7d12375
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	partition Dim_Contract = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://edfenergynnb.sharepoint.com/sites/L4Analysts/Shared%20Documents/L4%20Analysts/49.%20Contract%20Allocation/Contract%20Allocation.xlsx"), null, true),
				    ECSs_Sheet = Source{[Item="ECSs",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(ECSs_Sheet, [PromoteAllScalars=true]),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Promoted Headers", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers1",{{"ECS", type text}, {"Installation Contract", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Source of Information", "Contract Source"}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Renamed Columns",{{"ECS", Text.Upper, type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Uppercased Text", each [ECS] <> null and [ECS] <> ""),
				    #"Trimmed Text" = Table.TransformColumns(#"Filtered Rows",{{"ECS", Text.Trim, type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"ECS", Text.Clean, type text}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Cleaned Text", each [ECS] <> null and [ECS] <> ""),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows1", {"ECS"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

