table Dim_Resource_Profile
	excludeFromModelRefresh
	lineageTag: db760131-0231-45bd-a6a2-dade2ff4d8c5

	column 'Planning Commodity'
		dataType: string
		lineageTag: aa837522-90f3-4993-9147-40b91630e24b
		summarizeBy: none
		sourceColumn: Planning Commodity

		annotation SummarizationSetBy = Automatic

	column 'Resource ID'
		dataType: string
		lineageTag: bd3a7d2c-a1df-466d-a646-070de48757b2
		summarizeBy: none
		sourceColumn: Resource ID

		annotation SummarizationSetBy = Automatic

	column 'Resource Name'
		dataType: string
		lineageTag: 3f2ea1f5-fa77-46eb-bad0-e54d90c56714
		summarizeBy: none
		sourceColumn: Resource Name

		annotation SummarizationSetBy = Automatic

	column Trade
		dataType: string
		lineageTag: 417f0313-ce60-4a0b-adaa-882fe514c3d6
		summarizeBy: none
		sourceColumn: Trade

		annotation SummarizationSetBy = Automatic

	column %
		dataType: decimal
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 7a2e7e76-1234-4ab3-b979-e78bc26654c7
		summarizeBy: sum
		sourceColumn: %

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition Dim_Resource_Profile = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://edfenergynnb.sharepoint.com/sites/L4Analysts/Shared%20Documents/L4%20Analysts/00.%20Quantities/Commodities_Resource.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

