table Dim_Cable_Highways_Routes
	excludeFromModelRefresh
	lineageTag: 802414b5-25d9-4067-b97c-4f1a9c0fd839

	column 'Route building to building'
		dataType: string
		lineageTag: 186b1dba-656d-4a02-a288-924d2b2b7c59
		summarizeBy: none
		sourceColumn: Route building to building

		annotation SummarizationSetBy = Automatic

	column 'Route number'
		dataType: string
		lineageTag: 23e1cab7-f2b9-4335-ad7a-8d266a9e4a95
		summarizeBy: none
		sourceColumn: Route number

		annotation SummarizationSetBy = Automatic

	partition Dim_Cable_Highways_Routes = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://edfenergynnb.sharepoint.com/sites/L4Analysts/Shared%20Documents/L4%20Analysts/00.%20Quantities/Cabling%20Highways.xlsx"), null, true),
				    CH_Routes_Sheet = Source{[Item="CH_Routes",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(CH_Routes_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Route building to building", type text}, {"Route number", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each ([Route building to building] <> "BLANK"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

