table 'Dim_Activity (LIVE_P6)'
	lineageTag: 7da6ec83-0038-4120-ad9b-24f3d3ea0451

	column 'Project ID'
		dataType: string
		lineageTag: c715e85e-d4a8-4668-8971-24657e5a518e
		summarizeBy: none
		sourceColumn: Project ID

		annotation SummarizationSetBy = Automatic

	column 'Activity ID'
		dataType: string
		lineageTag: 7fa93aff-1fa0-4185-9ab0-2cfe48b42b2b
		summarizeBy: none
		sourceColumn: Activity ID

		annotation SummarizationSetBy = Automatic

	column 'Activity Name'
		dataType: string
		lineageTag: 253ab2e3-8a16-4d59-9a15-2af0711713c5
		summarizeBy: none
		sourceColumn: Activity Name

		annotation SummarizationSetBy = Automatic

	column 'Remaining Early Start'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ff1cbdc1-87ae-4e85-b31a-00850fb346de
		summarizeBy: none
		sourceColumn: Remaining Early Start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Remaining Early Finish'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2ad899c0-02d9-4cee-be1f-870a92e1d16c
		summarizeBy: none
		sourceColumn: Remaining Early Finish

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Late Start'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c42c0e0b-a443-49a4-b7ef-a2f4f752548b
		summarizeBy: none
		sourceColumn: Late Start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Late Finish'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6ea548c9-f086-4a6d-8871-2fcd3a6ed99b
		summarizeBy: none
		sourceColumn: Late Finish

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Free Float'
		dataType: double
		formatString: 0
		lineageTag: 46006126-2315-44fc-b7e2-3d01f9e8bafa
		summarizeBy: sum
		sourceColumn: Free Float

		annotation SummarizationSetBy = Automatic

	column 'Total Float'
		dataType: double
		formatString: 0
		lineageTag: 6d608e72-f173-4da4-879f-6a150c38e7e2
		summarizeBy: sum
		sourceColumn: Total Float

		annotation SummarizationSetBy = Automatic

	column Start
		dataType: dateTime
		formatString: Long Date
		lineageTag: b1b80f7c-a840-4478-96ae-8ec2ae3127b7
		summarizeBy: none
		sourceColumn: Start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Finish
		dataType: dateTime
		formatString: Long Date
		lineageTag: c19e73ff-d785-453b-b972-d7561a133731
		summarizeBy: none
		sourceColumn: Finish

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Column15
		dataType: string
		lineageTag: 7abf8fc8-225a-445e-946e-cd976021698c
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	partition 'Dim_Activity (LIVE_P6)' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://edfenergynnb.sharepoint.com/sites/L4Analysts/Shared%20Documents/L4%20Analysts/29.%20Schedule%20Activities/Activities%20LIVE.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Activities",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Promoted Headers", [PromoteAllScalars=true]),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Promoted Headers1", {"Activity ID"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Errors",{"Project ID", "Activity ID", "Activity Name", "Original Duration", "Remaining Duration", "Remaining Early Start", "Finish", "Budgeted Labor Units"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Reordered Columns"," A","",Replacer.ReplaceText,{"Finish"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","*","",Replacer.ReplaceText,{"Finish"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value1",{{"Remaining Early Start", type date}, {"Finish", type date}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type2",{"Budgeted Labor Units", "Original Duration", "Remaining Duration"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns1",{{"Remaining Late Finish", type date}}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Changed Type"," A","",Replacer.ReplaceText,{"Start"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","*","",Replacer.ReplaceText,{"Start"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value3",{{"Start", type date}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type3",{{"Remaining Late Finish", "Late Finish"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns1", {"Activity ID"}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Duplicates",{"Project ID", "Activity ID", "Activity Name", "Start", "Finish", "Remaining Early Start", "Remaining Early Finish", "Remaining Late Start", "Late Finish", "Free Float", "Total Float"}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Reordered Columns1",{{"Remaining Early Finish", type date}, {"Remaining Late Start", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type4",{{"Remaining Late Start", "Late Start"}}),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Renamed Columns",{{"Total Float", Int64.Type}, {"Free Float", Int64.Type}}),
				    #"Removed Duplicates1" = Table.Distinct(#"Changed Type5", {"Activity ID"}),
				    #"Removed Duplicates2" = Table.Distinct(#"Removed Duplicates1", {"Activity ID"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed Duplicates2", each [Activity ID] <> "1HLA3102ZL-.SSW.1HLA3103GM-"),
				    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows1", each [Activity ID] <> null and [Activity ID] <> ""),
				    #"Changed Type8" = Table.TransformColumnTypes(#"Filtered Rows2",{{"Project ID", type text}, {"Activity ID", type text}, {"Activity Name", type text}, {"Start", type date}, {"Finish", type date}, {"Remaining Early Start", type date}, {"Remaining Early Finish", type date}, {"Late Start", type date}, {"Late Finish", type date}, {"Free Float", type number}, {"Total Float", type number}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type8", {{"Start", null}}),
				    #"Replaced Errors1" = Table.ReplaceErrorValues(#"Replaced Errors", {{"Finish", null}}),
				    #"Replaced Errors2" = Table.ReplaceErrorValues(#"Replaced Errors1", {{"Activity Name", null}}),
				    #"Replaced Errors3" = Table.ReplaceErrorValues(#"Replaced Errors2", {{"Late Start", null}}),
				    #"Replaced Errors4" = Table.ReplaceErrorValues(#"Replaced Errors3", {{"Remaining Early Start", null}}),
				    #"Replaced Errors5" = Table.ReplaceErrorValues(#"Replaced Errors4", {{"Remaining Early Finish", null}})
				in
				    #"Replaced Errors5"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

