table Fact_%S
	excludeFromModelRefresh
	lineageTag: 2fd86fb8-f6ff-4068-8372-504c4336a1e3

	column WE
		dataType: dateTime
		formatString: Long Date
		lineageTag: fc6bf7ab-de8a-4607-9f1b-41f0bcc40ed0
		summarizeBy: none
		sourceColumn: WE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Working Weekend'
		dataType: string
		lineageTag: 71267398-3d53-46d4-a167-320aafcb31b8
		summarizeBy: none
		sourceColumn: Working Weekend

		annotation SummarizationSetBy = Automatic

	column 'Working Days'
		dataType: int64
		formatString: 0
		lineageTag: 5f6a81db-a4f8-4e6c-9ddf-6225a811474c
		summarizeBy: sum
		sourceColumn: Working Days

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 14e42e2e-8dd5-46be-93f3-5bf71f888140
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'TO4 Weekly Target'
		dataType: double
		lineageTag: 794e0c84-9ed6-48fb-a5b8-3a511e3538ee
		summarizeBy: sum
		sourceColumn: TO4 Weekly Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pattern 1 - 7d'
		dataType: double
		lineageTag: 3bdf779b-86a8-4520-8266-56b2ce7de4b7
		summarizeBy: sum
		sourceColumn: Pattern 1 - 7d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pattern 2 - 4d'
		dataType: double
		lineageTag: 0efc7336-d792-4d20-8e9f-e9d93f1c8639
		summarizeBy: sum
		sourceColumn: Pattern 2 - 4d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pattern 3 - '
		dataType: double
		lineageTag: 560c21d2-bd11-40aa-acef-61c84f954242
		summarizeBy: sum
		sourceColumn: "Pattern 3 - "

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'TO4 Weekly Progress Target WW'
		dataType: string
		lineageTag: 645a067b-0ce0-4240-9c5b-51bca3e339d5
		summarizeBy: none
		sourceColumn: TO4 Weekly Progress Target WW

		annotation SummarizationSetBy = Automatic

	column 'TO4 Weekly Target NW'
		dataType: string
		lineageTag: 5e3ed45a-f807-48de-a325-f2add226b8ad
		summarizeBy: none
		sourceColumn: TO4 Weekly Target NW

		annotation SummarizationSetBy = Automatic

	column 'Cum. TO4 Weekly Target'
		dataType: string
		lineageTag: 783856e8-470c-44b6-88b7-5d89802a4204
		summarizeBy: none
		sourceColumn: Cum. TO4 Weekly Target

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 05f6dfb3-8813-44c5-a316-c443d360f3f5
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fact_%S = m
		mode: import
		queryGroup: Actuals
		source =
				let
				
				    // Get Excel file from SharePoint (replaces File.Contents)
				    Source =
				        Excel.Workbook(Web.Contents("https://edfenergynnb.sharepoint.com/sites/L4Analysts/Shared%20Documents/L4%20Analysts/01.%20L4SPE%20Dashboards/TO4/MEH-26%20FC.xlsx"), null, true),
				
				    // Select the worksheet
				    Sheet =
				        Source{[Item = "Sheet1", Kind = "Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"WE", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","2025","2026",Replacer.ReplaceText,{"WE"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"Pattern 3 - ", type number}, {"Pattern 2 - 4d", type number}, {"Pattern 1 - 7d", type number}, {"TO4 Weekly Target", type number}, {"Q", type text}, {"Working Days", Int64.Type}, {"Working Weekend", type text}, {"WE", type date}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([WE] <> null)),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"WE", "Working Weekend", "Working Days", "Q", "TO4 Weekly Target", "Pattern 1 - 7d", "Pattern 2 - 4d", "Pattern 3 - ", "TO4 Weekly Progress Target WW", "TO4 Weekly Target NW", "Cum. TO4 Weekly Target"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "Month", each Date.StartOfMonth([WE])),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"Month", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type2",{{"Q", "Quarter"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

