table 'Fact_%S Sub-Area'
	excludeFromModelRefresh
	lineageTag: 32e9b5fe-74e1-4291-9cdf-4e6eb8533d29

	column 'Quarterly Forecast'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: aad129e3-3fa3-4979-9b53-4e67104eba3c
		summarizeBy: sum
		sourceColumn: Quarterly Forecast

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 72fb9366-38fe-40d3-b836-e93ff5c2c795
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'Working Days'
		dataType: string
		lineageTag: b3cdcaf0-883d-459d-beec-30dd1e063d22
		summarizeBy: none
		sourceColumn: Working Days

		annotation SummarizationSetBy = Automatic

	column 'Working Weeked'
		dataType: string
		lineageTag: 0ff58938-eaac-485d-ba69-3aefb9c06352
		summarizeBy: none
		sourceColumn: Working Weeked

		annotation SummarizationSetBy = Automatic

	column 'TO4 Weekly Target'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b06fd7e3-6fc1-4547-87df-0a3406cb4c97
		summarizeBy: sum
		sourceColumn: TO4 Weekly Target

		annotation SummarizationSetBy = Automatic

	column WE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8a0d56c5-3515-479f-b2d5-f7efb2d68242
		summarizeBy: none
		sourceColumn: WE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Sub-Area
		dataType: string
		lineageTag: 14bfe24c-a558-427c-a88f-5a3e8c16fd97
		summarizeBy: none
		sourceColumn: Sub-Area

		annotation SummarizationSetBy = Automatic

	partition 'Fact_%S Sub-Area' = m
		mode: import
		queryGroup: Actuals
		source =
				let
				
				    // Get Excel file from SharePoint (replaces File.Contents)
				    Source =
				        Excel.Workbook(Web.Contents("https://edfenergynnb.sharepoint.com/sites/L4Analysts/Shared%20Documents/L4%20Analysts/01.%20L4SPE%20Dashboards/TO4/MEH-26%20FC.xlsx"), null, true),
				
				    // Select the worksheet
				    Sheet =
				        Source{[Item = "%S by Sub-area", Kind = "Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"WE", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","2025","2026",Replacer.ReplaceText,{"WE"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value", each ([WE] <> null)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"WE", type date}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Month", each Date.StartOfMonth([WE])),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"Month", type date}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type2","Q","Qtr ",Replacer.ReplaceText,{"Quarter"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value1",{{"TO4 Weekly Target", type number}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type3",{"Quarterly Forecast", "Quarter", "Working Days", "Working Weeked", "TO4 Weekly Target", "WE", "Sub-Area"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

