table Welders
	excludeFromModelRefresh
	lineageTag: 986ca991-9e5b-48c1-8d0b-be99501af9e8

	column Code
		dataType: string
		lineageTag: 3c7fd097-16b7-4d49-bb87-05c76bfe7a04
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 93249286-d6b5-488e-b62a-166d2b2d3056
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	partition Welders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://edfenergynnb.sharepoint.com/sites/L4Analysts/Shared%20Documents/L4%20Analysts/00.%20Quantities/Welders.xlsx"), null, true),
				    Welders_Sheet = Source{[Item="Welders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Welders_Sheet, [PromoteAllScalars=true]),
				    #"Removed Other Columns" = Table.SelectColumns(#"Promoted Headers",{"Key", "Code"}),
				    #"Trimmed Text" = Table.TransformColumns(#"Removed Other Columns",{{"Key", Text.Trim, type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"Key", Text.Clean, type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Cleaned Text", {"Key"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Duplicates", each [Code] <> null and [Code] <> "")
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

